// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/15/2025, 9:42:16 PM
const configMerger = require("/Users/irek/sites/queensbingo/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/irek/sites/queensbingo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/plugins/**/*.{js,ts,mjs}","/Users/irek/sites/queensbingo/composables/**/*.{js,ts,mjs}","/Users/irek/sites/queensbingo/utils/**/*.{js,ts,mjs}","/Users/irek/sites/queensbingo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/irek/sites/queensbingo/app.config.{js,ts,mjs}"] }));

module.exports = config
